name: CI/CD Pipeline Net Monitor

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # PASO 1: Checkout del repositorio
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      # PASO 2: Login a Docker Hub
      - name: Login a Docker Hub
        uses: docker/login-action@v3
        with:
          username: gat0culia0
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # PASO 3: Build imagen app
      - name: Build imagen app
        run: |
          docker build -t gat0culia0/netmonitor-app:latest .

      # PASO 4: Build imagen nginx
      - name: Build imagen nginx
        run: |
          docker build -t gat0culia0/netmonitor-nginx:latest ./nginx

      # PASO 5: Push imágenes a Docker Hub
      - name: Push imágenes a Docker Hub
        run: |
          docker push gat0culia0/netmonitor-app:latest
          docker push gat0culia0/netmonitor-nginx:latest

      # PASO 6: Health Check HTTP (Prueba de infraestructura obligatoria)
      - name: Health Check HTTP
        run: |
          curl -f http://${{ secrets.EC2_PUBLIC_IP }}/

      # PASO 7: Latencia de red (Prueba de infraestructura obligatoria)
      - name: Latencia de red
        run: |
          curl -w '%{time_total}\n' -o /dev/null -s http://${{ secrets.EC2_PUBLIC_IP }}/

      # PASO 8: Validación de puerto (Prueba de infraestructura obligatoria)
      - name: Validación de puerto
        run: |
          nc -zv ${{ secrets.EC2_PUBLIC_IP }} 80

      # PASO 9: Deploy a ECS
      - name: Deploy a ECS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          aws ecs update-service --cluster netmonitor --service netmonitor-svc --force-new-deployment
